/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_PRIMITIVE_PRIMITIVE_PB_H_INCLUDED
#define PB_PRIMITIVE_PRIMITIVE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _primitive_Primitive {
    pb_size_t which_value;
    union {
        int32_t int_val;
        int64_t long_val;
        float float_val;
        double double_val;
        bool bool_val;
        char string_val[61];
    } value;
} primitive_Primitive;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define primitive_Primitive_init_default         {0, {0}}
#define primitive_Primitive_init_zero            {0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define primitive_Primitive_int_val_tag          1
#define primitive_Primitive_long_val_tag         2
#define primitive_Primitive_float_val_tag        3
#define primitive_Primitive_double_val_tag       4
#define primitive_Primitive_bool_val_tag         5
#define primitive_Primitive_string_val_tag       6

/* Struct field encoding specification for nanopb */
#define primitive_Primitive_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_val,value.int_val),   1) \
X(a, STATIC,   ONEOF,    INT64,    (value,long_val,value.long_val),   2) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_val,value.float_val),   3) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_val,value.double_val),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_val,value.bool_val),   5) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_val,value.string_val),   6)
#define primitive_Primitive_CALLBACK NULL
#define primitive_Primitive_DEFAULT NULL

extern const pb_msgdesc_t primitive_Primitive_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define primitive_Primitive_fields &primitive_Primitive_msg

/* Maximum encoded size of messages (where known) */
#define PRIMITIVE_PRIMITIVE_PB_H_MAX_SIZE        primitive_Primitive_size
#define primitive_Primitive_size                 62

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
