/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_REQUEST_PB_H_INCLUDED
#define PB_REQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Request {
    char metric_id[41];
} Request;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Request_init_default                     {""}
#define Request_init_zero                        {""}

/* Field tags (for use in manual encoding/decoding) */
#define Request_metric_id_tag                    1

/* Struct field encoding specification for nanopb */
#define Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   metric_id,         1)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL

extern const pb_msgdesc_t Request_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Request_fields &Request_msg

/* Maximum encoded size of messages (where known) */
#define REQUEST_PB_H_MAX_SIZE                    Request_size
#define Request_size                             42

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
